# -*- coding: utf-8 -*-
# gRPCServer/recommendation_pb2.py
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"C\n\x08UserBase\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x15\n\rinterest_tags\x18\x02 \x03(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"\x85\x01\n\x0fUserInteraction\x12+\n\tuser_base\x18\x01 \x01(\x0b\x32\x18.recommendation.UserBase\x12\x13\n\x0bquestion_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x02\x12\r\n\x05views\x18\x05 \x01(\x05\"K\n\x12InteractionRequest\x12\x35\n\x0cinteractions\x18\x01 \x03(\x0b\x32\x1f.recommendation.UserInteraction\"7\n\x13InteractionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x95\x01\n\x10RecommendRequest\x12+\n\tuser_base\x18\x01 \x01(\x0b\x32\x18.recommendation.UserBase\x12\x13\n\x0bquestion_id\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x12\r\n\x05views\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\r\n\x05top_n\x18\x06 \x01(\x05\"c\n\x0cQuestionInfo\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x02\x12\r\n\x05views\x18\x04 \x01(\x05\x12\x11\n\thot_score\x18\x05 \x01(\x02\"B\n\x11RecommendResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.recommendation.QuestionInfo2\xbb\x01\n\x0bRecommender\x12Z\n\x0fSendInteraction\x12\".recommendation.InteractionRequest\x1a#.recommendation.InteractionResponse\x12P\n\tRecommend\x12 .recommendation.RecommendRequest\x1a!.recommendation.RecommendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERBASE']._serialized_start=40
  _globals['_USERBASE']._serialized_end=107
  _globals['_USERINTERACTION']._serialized_start=110
  _globals['_USERINTERACTION']._serialized_end=243
  _globals['_INTERACTIONREQUEST']._serialized_start=245
  _globals['_INTERACTIONREQUEST']._serialized_end=320
  _globals['_INTERACTIONRESPONSE']._serialized_start=322
  _globals['_INTERACTIONRESPONSE']._serialized_end=377
  _globals['_RECOMMENDREQUEST']._serialized_start=380
  _globals['_RECOMMENDREQUEST']._serialized_end=529
  _globals['_QUESTIONINFO']._serialized_start=531
  _globals['_QUESTIONINFO']._serialized_end=630
  _globals['_RECOMMENDRESPONSE']._serialized_start=632
  _globals['_RECOMMENDRESPONSE']._serialized_end=698
  _globals['_RECOMMENDER']._serialized_start=701
  _globals['_RECOMMENDER']._serialized_end=888
# @@protoc_insertion_point(module_scope)
