# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
# gRPCServer/recommendation_pb2_grpc.py
import grpc
import warnings

import recommendation_pb2 as recommendation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommenderStub(object):
    """/ =========================
    /    gRPC 服务定义
    / =========================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendInteraction = channel.unary_unary(
                '/recommendation.Recommender/SendInteraction',
                request_serializer=recommendation__pb2.InteractionRequest.SerializeToString,
                response_deserializer=recommendation__pb2.InteractionResponse.FromString,
                _registered_method=True)
        self.Recommend = channel.unary_unary(
                '/recommendation.Recommender/Recommend',
                request_serializer=recommendation__pb2.RecommendRequest.SerializeToString,
                response_deserializer=recommendation__pb2.RecommendResponse.FromString,
                _registered_method=True)


class RecommenderServicer(object):
    """/ =========================
    /    gRPC 服务定义
    / =========================
    """

    def SendInteraction(self, request, context):
        """/ (A) 用户交互上报
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recommend(self, request, context):
        """/ (B) 请求推荐
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInteraction,
                    request_deserializer=recommendation__pb2.InteractionRequest.FromString,
                    response_serializer=recommendation__pb2.InteractionResponse.SerializeToString,
            ),
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=recommendation__pb2.RecommendRequest.FromString,
                    response_serializer=recommendation__pb2.RecommendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.Recommender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.Recommender', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Recommender(object):
    """/ =========================
    /    gRPC 服务定义
    / =========================
    """

    @staticmethod
    def SendInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.Recommender/SendInteraction',
            recommendation__pb2.InteractionRequest.SerializeToString,
            recommendation__pb2.InteractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.Recommender/Recommend',
            recommendation__pb2.RecommendRequest.SerializeToString,
            recommendation__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
